syc_system/syc_system/urls.py
from django.contrib import admin
from django.urls import path
from purchase import views as purchase_views
from storage import views as storage_views
from report import views as report_views
from basic_info import views as basic_info_views
from system_maintain import views as system_maintain_views

urlpatterns = [
    path(r'admin/', admin.site.urls),


    path(r'', purchase_views.show_purchase_index),
    path(r'purchase_index/', purchase_views.ShowPurchaseIndex.as_view(), name='purchase_index'),
    # path(r'create_purchase_order/', purchase_views.CreatePurchaseOrder.as_view(), name='create_purchase_order'),


    path(r'storage_index/', storage_views.ShowStorageIndex.as_view(), name='storage_index'),


    path(r'report_index/', report_views.ShowReportIndex.as_view(), name='report_index'),


    path(r'basic_info_index/', basic_info_views.ShowBasicInfoIndex.as_view(), name='basic_info_index'),
    path(r'basic_info/customer_info/', basic_info_views.ShowCustomerInfo.as_view(), name='customer_info'),
    path(r'basic_info/upload_customer_info/', basic_info_views.UploadCustomerInfo.as_view(), name='upload_customer_info'),
    path(r'basic_info/add_customer_info/', basic_info_views.AddCustomerInfo.as_view(), name='add_customer_info'),
    path(r'basic_info/modify_customer_info/', basic_info_views.ModifyCustomerInfo.as_view(), name='modify_customer_info'),
    path(r'basic_info/delete_customer_info/', basic_info_views.DeleteCustomerInfo.as_view(), name='delete_customer_info'),


    path(r'system_maintain_index/', system_maintain_views.ShowSystemMaintainIndex.as_view(),
         name='system_maintain_index'),


]

syc_system/basic_info/models.py
from django.db import models

# Create your models here.


class CustomerInfo(models.Model):
    location = models.CharField(max_length=128, verbose_name='地区')
    name = models.CharField(max_length=64, verbose_name='姓名')
    mobilephones = models.CharField(max_length=64, verbose_name='手机号')
    address = models.CharField(max_length=512, verbose_name='地址')
    phone = models.CharField(max_length=64, verbose_name='座机')
    default_rebate = models.IntegerField(default=100, verbose_name='折扣')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')

    class Meta:
        db_table = 'syc_customer_info'
        verbose_name = verbose_name_plural = '客户信息'

    @classmethod
    def get_all_customer_info(cls):
        return cls.objects.filter(is_delete=False)

    @classmethod
    def get_appointed_customer_info(cls, condition):
        if condition:
            customer_list = [i for i in cls.get_all_customer_info() if condition in (i.location + i.name)]
            if customer_list:
                return customer_list
        return cls.get_all_customer_info()

    @classmethod
    def get_customer_info(cls, cust_id):
        try:
            customer_info = cls.objects.get(pk=int(cust_id))
        except Exception as e:
            print(e)
            return None
        else:
            return customer_info

    @classmethod
    def delete_customer_info(cls, cust_id):
        customer_info = cls.get_customer_info(cust_id)
        if customer_info:
            customer_info.is_delete = True
            customer_info.save()
        else:
            print('客户不存在...')


class CustomerRank(models.Model):
    order_count = models.IntegerField(default=0, verbose_name='订单数')
    balance = models.FloatField(default=0.00, verbose_name='余额')
    total_income =  models.FloatField(default=0.00, verbose_name='总金额')
    total_pro_count = models.IntegerField(default=0, verbose_name='总产品数')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modify_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    is_delete = models.BooleanField(default=True, verbose_name='是否删除')
    customer_info = models.OneToOneField(CustomerInfo, on_delete=models.CASCADE, verbose_name='客户信息')

    class Meta:
        db_table = 'syc_customer_rank'
        verbose_name = verbose_name_plural = '客户排名'


class UserInfo(models.Model):
    user_name = models.CharField(max_length=64, verbose_name='用户名')
    telephone_number = models.CharField(max_length=64, verbose_name='手机号')
    level = models.IntegerField(default=0, verbose_name='用户等级')
    comment = models.CharField(max_length=256, verbose_name='用户备注')
    password = models.CharField(max_length=128, verbose_name='密码')
    sign_in_token = models.CharField(max_length=128, verbose_name='token')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')

    class Meta:
        db_table = 'syc_user_info'
        verbose_name = verbose_name_plural = '用户信息'

syc_system/basic_info/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from basic_info.form import AddCustomerInfoForm
from basic_info.helper import OperateCustomerInfo
from basic_info.models import CustomerInfo
from common.base_forms import SearchLocationOrNameForm, UploadFileForm
from common.excel_operate import translate_excel_data
from common.file_operate import create_customer_info_file


class ReportBaseView(View):
    data = dict()
    json_data = dict()
    data['basic_info_title'] = 'active'


class ShowBasicInfoIndex(ReportBaseView):
    def get(self, request):
        self.data['title'] = '基本资料'
        return render(request, 'basic_info_index.html', self.data)


class ShowCustomerInfo(ReportBaseView):
    def get(self, request):
        form_search = SearchLocationOrNameForm(request.GET)
        form_file = UploadFileForm()
        if form_search.is_valid():
            self.data['offset'] = request.GET.get('offset', '')
            self.data['title'] = '客户资料'
            self.data['search_condition'] = form_search
            self.data['upload_file'] = form_file
            self.data['customer_infos'] = CustomerInfo.get_appointed_customer_info(condition=form_search.data.get('search_condition', None))
            return render(request, 'customer_info.html', self.data)
        else:
            return HttpResponse('请正确访问...')


class UploadCustomerInfo(ReportBaseView):
    def post(self, request):
        form_file = UploadFileForm(request.POST, request.FILES)
        if form_file.is_valid():
            fr = form_file.files.get('upload_file')
            file_path = create_customer_info_file(fr)
            data_lt, check_word = translate_excel_data(file_path)
            if check_word == '客户资料':
                try:
                    OperateCustomerInfo.bulk_create_customer_info(data_lt)
                except Exception as e:
                    print('error', e)
                    self.json_data['code'] = 'error'
                else:
                    self.json_data['code'] = 'ok'
            else:
                self.json_data['code'] = 'error'
            return JsonResponse(self.json_data)


class AddCustomerInfo(ReportBaseView):
    def get(self, request):
        forms = AddCustomerInfoForm()
        self.data['input_forms'] = forms
        self.data['action'] = reverse('add_customer_info')
        return render(request, 'add_or_upgrate_customer_info.html', self.data)

    def post(self, request):
        forms = AddCustomerInfoForm(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect(reverse('customer_info') + '?offset=100000')
        else:
            return redirect(reverse('customer_info'))


class ModifyCustomerInfo(ReportBaseView):
    def get(self, request):
        cust_id = request.GET.get('cust_id')
        cust_id = int(cust_id) if cust_id.isdigit() else None
        customer_info = CustomerInfo.get_customer_info(cust_id)
        forms = AddCustomerInfoForm(instance=customer_info)
        self.data['input_forms'] = forms
        self.data['action'] = reverse('modify_customer_info')
        self.data['cust_id'] = cust_id
        return render(request, 'add_or_upgrate_customer_info.html', self.data)

    def post(self, request):
        forms = AddCustomerInfoForm(request.POST)
        cust_id = request.POST.get('cust_id')
        cust_id = int(cust_id) if cust_id.isdigit() else None
        customer_info = CustomerInfo.get_customer_info(cust_id)
        if forms.is_valid():
            form = AddCustomerInfoForm(request.POST, instance=customer_info)
            form.save()
            return redirect(reverse('customer_info') + '?offset=100000')
        else:
            return redirect(reverse('customer_info'))


class DeleteCustomerInfo(ReportBaseView):
    def get(self, request):
        offset = request.GET.get('offset')
        cust_id = request.GET.get('cust_id')
        cust_id = int(cust_id) if cust_id.isdigit() else None
        CustomerInfo.delete_customer_info(cust_id)
        return redirect(reverse('customer_info') + '?offset=' + offset)

syc_system/basic_info/templates/add_or_upgrate_customer_info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{{ title }}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/basic_info/add_or_upgrate_customer_info.css' %}">
</head>
<body>


<form action="{{ action }}" class="form-inline" method="post" id="submit_customer_info_form">
    {% csrf_token %}
    <br><br>
    <div class="form-group col-md-12 form_content">
        <label for="id_location">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;区：</label>
        {{ input_forms.location }}
    </div>
    <div class="form-group col-md-12 form_content">
        <label for="id_name">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名：</label>
        {{ input_forms.name }}
    </div>
    <div class="form-group col-md-12 form_content">
        <label for="id_mobilephones">联系方式：</label>
        {{ input_forms.mobilephones }}
    </div>
    <div class="form-group col-md-12 form_content">
        <label for="id_phone">座&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;机：</label>
        {{ input_forms.phone }}
    </div>
    <div class="form-group col-md-12 form_content">
        <label for="id_address" style="vertical-align: top">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：</label>
        {{ input_forms.address }}
    </div>
    <div class="form-group col-md-12 form_content">
        <label for="id_default_rebate">折&nbsp;&nbsp;&nbsp;&nbsp;扣%：</label>
        {{ input_forms.default_rebate }}
    </div>
    <br>
    <input type="text" name="cust_id" style="display: none" value="{{ cust_id }}">
    <div class="form-group col-md-12" id="submit_customer_info_btn">
        <button type="submit" class="btn btn-primary">提交</button>
        <button type="reset" class="btn btn-primary">重置</button>
    </div>
</form>


<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/confirm_action.js' %}"></script>
<script type="text/javascript" src="{% static 'js/basic_info/add_or_upgrate_customer_info.js' %}"></script>
</body>
</html>

syc_system/basic_info/templates/customer_info.html
{% extends 'base_main.html' %}
{% load static %}



{% block ex_css %}
    <link rel="stylesheet" href="{% static 'css/basic_info/customer_info.css' %}">
{% endblock %}



{% block ex_js %}
    <script src="{% static 'js/basic_info/customer_info.js' %}"></script>
{% endblock %}



{% block body_header %}
    <input id="offset" type="text" value="{{ offset }}" style="display: none;">
    <div class="container-fluid" id="customer_info_content_div">
        <div id="customer_info_content_inner_div">
            <div class="row">
                <div class="col-md-11 col-xs-10">
                    <form class="form-inline" method="get" action="{% url 'customer_info' %}" id="customer_search_form">
                        <div class="form-group">
                            {{ search_condition }}
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit" id="search_btn">查询</button>
                            <button class="btn btn-primary" type="button" id="add_btn"
                                    data-addCustomerInfoURL="{% url 'add_customer_info' %}">添加
                            </button>
                            <button class="btn btn-primary" type="button" id="upload_btn"
                                    data-fileURL="{% url 'upload_customer_info' %}">导入
                            </button>
                        </div>
                    </form>
                    <form id="upload_file_form" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ upload_file }}
                    </form>
                </div>
            </div>
            <br>
            <div class="row table_head">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th></th>
                        <th width="100px">地区</th>
                        <th width="100px">姓名</th>
                        <th width="130px">联系电话</th>
                        <th width="130px" class="pre_hidden">座机</th>
                        <th width="400px" class="pre_hidden">地址</th>
                        <th width="80px">折扣%</th>
                        <th width="150px">操作</th>
                        <th></th>
                    </tr>
                    </thead>
                </table>
            </div>

            <div class="row table_body">
                <table class="table table-striped">
                    <tbody>

                    {% for foo in customer_infos %}
                        <tr>
                            <td></td>
                            <td width="100px">{{ foo.location }}</td>
                            <td width="100px">{{ foo.name }}</td>
                            <td width="130px">{{ foo.mobilephones }}</td>
                            <td width="130px" class="pre_hidden">{{ foo.phone }}</td>
                            <td width="400px" class="pre_hidden">{{ foo.address }}</td>
                            <td width="80px">{{ foo.default_rebate }}</td>
                            <td width="150px" cust_id="{{ foo.id }}"
                                data-modifyCustomerInfoURL="{% url 'modify_customer_info' %}"
                                data-deleteCustomerInfoURL="{% url 'delete_customer_info' %}"><a
                                    class="modify_customer_info" href="">修改</a> | <a class="delete_customer_info"
                                                                                     href="">删除</a></td>
                            <td></td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>
    </div>
{% endblock %}



{% block body_body %}

{% endblock %}



{% block body_footer %}

{% endblock %}